version: '2'
services:
  freepbx:
    container_name: freepbx
    image: sudolio/freepbx
    restart: always
    ports:
    - "8080:80"
    - "5060:5060"
    - "5060:5060/udp"
    - "5061:5061"
    - "5160:5160"
    - "5160:5160/udp"
    - "5161:5161"
    - "9001:9001"
    - "10000-10050:10000-10050/udp"
    volumes:
    - config:/etc/asterisk
    - log:/var/log
    - data:/var/spool/asterisk
    environment:
    - DB_HOST=db
    - DB_PORT=3306
    - DB_NAME=freepbx
    - DB_USER=root
    - DB_PASS=
    - RTP_PORT_START=10000
    - RTP_PORT_END=10050
    - EXTRA_MODULES=ivr certman
    - SUPERVISOR_PASSWORD=admin
    depends_on:
    - db
  db:
    image: "mariadb:10.3.9-bionic"
    volumes:
    - db:/var/lib/mysql
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=1
    - MYSQL_ROOT_PASSWORD=
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
    - 8081:80
    volumes:
    - /sessions
    environment:
    - PMA_USER=root
    - PMA_PASSWORD=
volumes:
  config:
  log:
  data:
  db: